/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EDD;

import static EDD.ManejoArchivo.escribirArchivo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author valef
 */
public class NuevaSesion extends javax.swing.JFrame {
      private String[] sesion = new String[7];
    /**
     * Creates new form NS
     */
    public NuevaSesion() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        especialidad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        agendar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        entrenador = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(48, 48, 48));

        volver.setBackground(new java.awt.Color(244, 179, 36));
        volver.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 179, 36));
        jLabel1.setText("Nombre Completo");

        nombre.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 73, 2), 3));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 179, 36));
        jLabel2.setText("N° Documento de Identidad");

        cedula.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        cedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 73, 2), 3));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(244, 179, 36));
        jLabel3.setText("Especialidad Deportiva");

        especialidad.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la especialidad", "Fuerza", "Velocidad", "Resistencia", "Flexibilidad", "Fisioterapia" }));
        especialidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 73, 2), 3));
        especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 73, 2));
        jLabel4.setText("REGISTRO");

        agendar.setBackground(new java.awt.Color(241, 73, 2));
        agendar.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        agendar.setText("AGENDAR");
        agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(244, 179, 36));
        jLabel5.setText("Entrenador Asignado");

        entrenador.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        entrenador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su entrenador", "María Gómez", "Carlos López", "Ana Martínez", "Luis Rodríguez", "Sofía Díaz", "Jorge Ruiz", "Laura Sánchez", "Diego Ramírez", "Mónica Torres", "Pedro Jiménez", "Carmen Vargas", "Andrés Castro", "Patricia Mora", "Ricardo Soto" }));
        entrenador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 73, 2), 3));
        entrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrenadorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nueva Sesión de Entrenamiento");

        jLabel7.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(244, 179, 36));
        jLabel7.setText("Hora");

        jLabel8.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(244, 179, 36));
        jLabel8.setText("Fecha Agendada");

        hora.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        hora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 73, 2), 3));
        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });

        fecha.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 73, 2), 3));
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(103, 103, 103)
                        .addComponent(especialidad, 0, 450, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(152, 152, 152)
                        .addComponent(cedula))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(39, 39, 39)
                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(volver)
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(volver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nombre)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static void filtrarEntrenadores(String[] ed, String especialidad, JComboBox entrenador){
       entrenador.removeAllItems(); 
       File archivo = new File("entrenadores.txt");
       int i=0;
        try {
            BufferedReader entrada = new BufferedReader(new FileReader(archivo));
            String lectura;
            while((lectura= entrada.readLine())!= null){
                String[] p = lectura.split(",");  
                if((p[2].equals(especialidad)) && Integer.parseInt(p[4])<15){
                    ed[i]= p[0];
                    i++;
                }
            }
            for(int j =0; j< ed.length; j++){
                        if(ed[j]!= null){
                            entrenador.addItem(ed[j]);
                        }
                    }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManejoArchivo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManejoArchivo.class.getName()).log(Level.SEVERE, null, ex);
        }
   }

    private void especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadActionPerformed
        String[] entrenadoresdisponibles = new String [20];
        try{
            switch(especialidad.getSelectedIndex()){
                case 0:
                    entrenador.removeAllItems();
                    entrenador.addItem("Seleccionar Entrenador");
                    break;
                case 1: 
                    //Fuerza
                    filtrarEntrenadores(entrenadoresdisponibles, "Fuerza", entrenador);
                    break;
                case 2:
                    //Velocidad
                    filtrarEntrenadores(entrenadoresdisponibles, "Velocidad", entrenador);
                    break;
                case 3:
                    //Resistencia
                    filtrarEntrenadores(entrenadoresdisponibles, "Resistencia", entrenador);
                    break;
                case 4:
                    //Flexibilidad
                    filtrarEntrenadores(entrenadoresdisponibles, "Flexibilidad", entrenador);
                    break;
                case 5:
                    //Fisioterapia
                    filtrarEntrenadores(entrenadoresdisponibles, "Fisioterapia", entrenador);
                    break;
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Los datos ingresados no son válidos", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_especialidadActionPerformed

    private void entrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrenadorActionPerformed
        
    }//GEN-LAST:event_entrenadorActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarActionPerformed
     String[] datos = guardarinfo();
    
    if (datos != null) {
        escribirArchivo("sesiones.txt", datos);
        nombre.setText("");
        cedula.setText("");
        fecha.setText("");
        hora.setText("");
        especialidad.setSelectedIndex(0);
        entrenador.setSelectedIndex(0);
        
        JOptionPane.showMessageDialog(this, "Sesión agendada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }
    
    }//GEN-LAST:event_agendarActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed
   private boolean validarDatos() {
         String nombreIngresado = nombre.getText().trim();
         String cedulaIngresada = cedula.getText().trim();

         // This is the fix - change hora.getText() to fecha.getText()
         String fechaIngresada = fecha.getText().trim();  // FIXED LINE
         String horaIngresada = hora.getText().trim();

         String especialidadSeleccionada = (String) especialidad.getSelectedItem();
         String entrenadorSeleccionado = (String) entrenador.getSelectedItem();

         //Validar que ningún campo esté vacío
         if (nombreIngresado.isEmpty() || cedulaIngresada.isEmpty() || fechaIngresada.isEmpty() || 
             horaIngresada.isEmpty() || especialidadSeleccionada.equals("Seleccione la especialidad") || 
             entrenadorSeleccionado.equals("Seleccione el entrenador")) {

             JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }

         // Validar nombre (solo letras y espacios)
         if (!nombreIngresado.matches("^[A-Za-zÁÉÍÓÚáéíóúñÑ ]+$")) {
             JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras y espacios", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }

         // Validar fecha (formato dd-MM-yyyy)
         if (!validarFormatoFecha(fechaIngresada, "dd-MM-yyyy")) {
             JOptionPane.showMessageDialog(this, "La fecha debe estar en formato dd-MM-yyyy", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }

         // Validar hora (formato HH:mm)
         if (!validarFormatoFecha(horaIngresada, "HH:mm")) {
             JOptionPane.showMessageDialog(this, "La hora debe estar en formato HH:mm", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }

         return true; // Si pasa todas las validaciones
    }

    private boolean validarFormatoFecha(String fecha, String formato) {
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        sdf.setLenient(false); // Evita fechas inválidas como 32-13-2024
        try {
            sdf.parse(fecha);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }
    private static int generarNumeroAleatorio() {
        Random random = new Random();
        return random.nextInt(99999) + 10000; // Genera un número entre 10000 y 99999
    }
     public String[] guardarinfo(){
      if (validarDatos()) {
        sesion[0] = String.valueOf(generarNumeroAleatorio());
        sesion[1] = nombre.getText().trim();
        sesion[2] = cedula.getText().trim();
        sesion[3] = (String) especialidad.getSelectedItem();
        sesion[4] = (String) entrenador.getSelectedItem();
        sesion[5] = fecha.getText().trim();
        sesion[6] = hora.getText().trim();
        return sesion;
      } else{
        return null;
      }
         
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendar;
    private javax.swing.JTextField cedula;
    private javax.swing.JComboBox<String> entrenador;
    private javax.swing.JComboBox<String> especialidad;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
